apiVersion: 1

datasources:
  - name: Platform PostgreSQL Readonly
    uid: platform-postgres-readonly
    type: postgres
    access: proxy
    url: ${GRAFANA_POSTGRES_HOST}:${GRAFANA_POSTGRES_PORT}
    database: ${GRAFANA_POSTGRES_DB}
    user: ${GRAFANA_POSTGRES_USER}
    secureJsonData:
      password: ${GRAFANA_POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    editable: false
